### ISSUE TITLE
Arrumar o slide dos parceiros

### ISSUE THREAD

**Issue by jonathandetoni** [time-jobis/landing-page-curriculo#8]
As imagens não estão chegando até o final da `<div class="container">`. Tem que ajustar para que fique até o final.

**Comment by andrecb** [comment]
Eu verifiquei aqui e tá normal mano

**Comment by jonathandetoni** [comment]
Quando estava com 5, ele não terminava junto com o container. 

Acho que o Pessanha vai querer que você tire aquelas setas, só uma suposição kkkkk
